version: "3.8"

services:
  uv-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: bmed-NN
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true