version: "3.9"
services:
  torch-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    working_dir: /app
    shm_size: 8gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true
    stdin_open: true
    restart: unless-stopped
