services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"  # Jupyter Notebook 포트 매핑
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity